### ISSUE TITLE
If you had to invent another language*, against your will...

### ISSUE THREAD

**Issue by assertchris** [hafriedlander/ama#3]
What would it look like?
- We're talking programming language, because we're boring like that.

**Comment by hafriedlander** [comment]
I have thought about this before (I think most programmers have).

My ideal language to program in would be basically ECMAScript, but without the `function` keyword (I think in most cases you could just start a function like `(){ /* code goes here */ }` without parser ambiguousness, so you can just drop the keyword) and with full co-routines.

However that's _pretty_ close to what ECMAScript 6 already is (you can fake co-routines with generators & a trampoline), so no need to go spending time doing that.

I did write a transpiler that turned JavaScript into JavaScript + co-routines, but it never really got used. The generated code was about 33% bigger at the byte level, and at the time there weren't sourcemaps or any of the other nice tooling to deal with transpiled code in the browser.

Something I don't think has been explored much is pattern matching typed languages. I like dynamically typed languages. I don't like statically typed languages (at least the braindead sort of static typing that Java / PHP / etc do - apparent Haskell might be actually OK at types?). The reason is because types are rarely unary things - any particular instance or item or variable can act like a bunch of different types at the same time. In other words, duck typing. Static type systems don't really allow duck typing - representing it through an inheritance hierarchy, interfaces, etc, is messy.

But if you could codify duck typing, and say "this is what a duck looks like, anything that matches these rules can be treated like a duck", that would be cool, and a type system I could get into. Sort of like interfaces, only you wouldn't ever have to say "this object implements interface X" - the language would just look at the interface, and the object, and say "yup, that looks like an X all right".

No idea if this is practical, or has already been done, or whatever, but right now if I had to invent a language, I'd invent a pattern matching typed one. Although I'd probably have to spend time learning things like Haskell to avoid reinventing the wheel, which turns me right off the whole idea.

**Comment by assertchris** [comment]
So, Go?

**Comment by hafriedlander** [comment]
More programmatic than just "has all these methods though".

An example is something like `function (float $a, float $b) { return $a / $b; }`; Ideally you want $b's type to be "a float, but not 0".

If you could do

```
type non-zero-float {
    like float;
    != 0;
}

function (float $a, non-zero-float $b) { return $a / $b; }
```

that'd be cool. Bonus points for a readable syntax that didn't need a separate type definition block before the function definition. It'd need to work for classes as well as scalars of course. I haven't done enough Go to know if it can do that?

Oh, also, types would need to be first-class entities, so they could be defined at run-time.

**Comment by assertchris** [comment]
Maybe...

```
(float $a, float != 0 $b) { return $a / $b; }
```

**Comment by hafriedlander** [comment]
Of course, that's a very sensible answer, but not very funny. So I present horse/duck. horse/duck is an encoding of [subleq](https://esolangs.org/wiki/Subleq), a one-instruction computer. `horse` represents a byte separator. The number of `duck`s between each `horse` is counted, and the count is the value of that byte.

```
duck duck duck horse duck duck horse duck
```

Is

```
3 2 1 
```

Implementing hello world in horse/duck is left as an exercise to the reader.

**Comment by assertchris** [comment]
hah.

**Comment by hafriedlander** [comment]
Is [this](https://github.com/hafriedlander/horseduck) the least useful language ever? Yes, I think it is.
