### ISSUE TITLE
What's your favorite place on earth and why?

### ISSUE THREAD

**Issue by sindresorhus** [hafriedlander/ama#6]

**Comment by hafriedlander** [comment]
My instinctual answer would be to answer places I've visited, and enjoyed, but didn't stay for long. I really enjoyed recent trips to Rome and Venice - just incredible spaces to explore - but I only spent a couple of days in each, so it's hard to say they'd be my favourite places. 

Similarly, I really enjoyed a recent visit to Las Vegas, but when I left I felt like if I had stayed another day I would of died - hard to say any place that can kill you so quickly is a favourite.

What I really enjoyed about all those examples was the experience, rather than the place. So, favourite place: the future.
