### ISSUE TITLE
What was the most difficult math or physics problem that you ever resolved?

### ISSUE THREAD

**Issue by aarroyoc** [hafriedlander/ama#8]

**Comment by hafriedlander** [comment]
Wow, I've been bad about following this up. Anyway, umm...

Math is a pretty wide area. Normally the most complex math I do is algebraic / geometric rather than calculus (if I need to know the derivative of something, these days I just cheat and ask Wolfram Alpha).

The most difficult thing recently, I had to write an arbitrary constraints solver for a 2D CAD program. The user could specify a shape like "this is a shape with four sides, one side is 100mm long, next one is at a right angle and is 200mm long", etc. There may or may not be enough constraints provided to resolve to a single shape (or there might be too many, to the point that no shape could possibly meet the constraints), and those conditions needed to be detected & handled nicely. No lines could overlap, but the shape wasn't necessarily convex.

So I had to convert the constraints into a set of simultaneous equations, and then solve them. I could have done this directly in code if they were all linear equations, but of course they weren't. I still tried initially, but writing code to solve 10 - 20 semi-arbitrary simultaneous equations, some of which involved trigonometry and all of which involved exponents seemed pretty non-trivial. I ended up writing code that searched the problem space for a good solution, starting with one of a set of known shapes that was "best", then adjusting parameters until a complete solution was found. I think the math needed still ended up being more than most developers I know would feel comfortable with.

So if the first derivative of this question is: "do I feel like knowing math is important to web development?" - it's not essential, but it helps, sometimes a lot. I don't think there's any level where it stops being relevant (although you will get diminishing returns).
