### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [hafriedlander/ama#9]

**Comment by hafriedlander** [comment]
Not usually in an externally open way. Internal to SilverStripe, my employer, a lot of my job responsibility is working with both our Solutions Architects and all our devs generally as a mentor and coach. So yes, because it's my job :).

I'm not a great direct skill teacher though - I get frustrated if the student doesn't understand a concept I'm trying to explain. And there's very little that irritates me as much as being asked something as a subject expert, me giving an answer, and then the asker saying "oh, I don't agree with that" and ignoring it. (side-note, Management 3.0 has this concept of apprentices being taught by journeymen better than by masters, so I think this isn't just a problem for me :)). 

So I work with my strengths and use a more sort of socratic / collaborative style where I try and get whoever I'm working with to solve the problem themselves, giving an outside viewpoint, suggesting resources and only getting directly involved when they seem stuck.

That also seems to work better with developers, who (stereotyping) are an opinionated lot who tend to respond badly to being told they need to do something a specific way. It can frustrate some people though, since it can come off as needlessly obtuse and/or lazy - they're looking for answers, not more questions.

I don't seek out people interesting in being mentored outside of work though. This is probably a mix of natural introverted tendencies, imposter syndrome, laziness and arrogance (I literally can't think of anyone I would like to mentor me - lots of people I'd love to work with and/or be friends with and/or help out with specific things but that's a bit different).
